const TYPES = {
  IUserRepository: Symbol.for("IUserRepository"),
  ITicketRepository: Symbol.for("ITicketRepository"),
  AuthService: Symbol.for("AuthService"),
  LoginUseCase: Symbol.for("LoginUseCase"),
  LogoutUseCase: Symbol.for("LogoutUseCase"),
  AuthController: Symbol.for("AuthController"),
  CreateTicketUseCase: Symbol.for("CreateTicketUseCase"),
  TicketController: Symbol.for("TicketController"),
  ListTicketsUseCase: Symbol.for("ListTicketsUseCase"),
  GetTicketUseCase: Symbol.for("GetTicketUseCase"),
  UpdateTicketUseCase: Symbol.for("UpdateTicketUseCase"),
  DeleteTicketUseCase: Symbol.for("DeleteTicketUseCase"),
  SearchTicketsUseCase: Symbol.for("SearchTicketsUseCase"),
  ICommentRepository: Symbol.for("ICommentRepository"),
  AddCommentUseCase: Symbol.for("AddCommentUseCase"),
  GetCommentsUseCase: Symbol.for("GetCommentsUseCase"),
  CommentController: Symbol.for("CommentController"),
  IKnowledgeBaseRepository: Symbol.for("IKnowledgeBaseRepository"),
  ListArticlesUseCase: Symbol.for("ListArticlesUseCase"),
  GetArticleUseCase: Symbol.for("GetArticleUseCase"),
  KnowledgeBaseController: Symbol.for("KnowledgeBaseController"),
};
export default TYPES;
